### PR TITLE
refund doc correction

### PR DESCRIPTION
**Pull request by ankitdas13**
Doc reference : https://razorpay.com/docs/api/refunds

### CODE REVIEW

**Comment by ankitdas13** [comment]
> 1. Create a normal refund - response "speed_requested": "normal" missing
> 2. Create an instant refund - 'speed_processed': 'normal' missing
>    Check above both api in post as with speed and receipt parameter its throwing error

@sofiya02 i have updated the response parameter and put receipt parameters unique while call this two api's

**Review by sofiya02 — CHANGES_REQUESTED** [review]
create a norma refund and instant refund please correct receipt no 132

**Comment by ankitdas13** [comment]
> create a normal refund and instant refund please correct receipt no 132

[Added](https://github.com/razorpay/razorpay-python/blob/refund_doc_correction/documents/refund.md?plain=1#L39)

**Review by sofiya02 — APPROVED** [review]
LGTM

**Pull request merged**
